# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/hypnoglow/helm-s3
    steps:
      - checkout
#      - run: go get -u -v github.com/golang/dep/cmd/dep
#      - run: dep ensure -v
      - run: ./.circleci/testcover.sh
      - run: bash <(curl -s https://codecov.io/bash)
      - run: go build ./cmd/...
      - deploy:
          name: goreleaser
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              curl -sL https://git.io/goreleaser | bash
            fi